name = "ItemResponseFunctions"
uuid = "18e85bec-f2a0-4122-b3a6-37651333b522"
authors = ["Philipp Gewessler <p.gewessler@gmx.at>"]
version = "0.1.0"

[deps]
AbstractItemResponseModels = "0ab3451c-659c-47cd-a7a9-a2d579e209dd"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
AbstractItemResponseModels = "0.2"
