name = "ItemResponseFunctions"
uuid = "18e85bec-f2a0-4122-b3a6-37651333b522"
authors = ["Philipp Gewessler <p.gewessler@gmx.at>"]
version = "0.1.7"

[deps]
AbstractItemResponseModels = "0ab3451c-659c-47cd-a7a9-a2d579e209dd"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"

[compat]
AbstractItemResponseModels = "0.2"
DifferentiationInterface = "0.5, 0.6"
DocStringExtensions = "0.9"
ForwardDiff = "0.10"
LogExpFunctions = "0.3"
PrecompileTools = "1"
Reexport = "1"
SimpleUnPack = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
